// <auto-generated />
using ExamWeb_HuynhVanTruong.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ExamWeb_HuynhVanTruong.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ExamWeb_HuynhVanTruong.Models.DiaNhac", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("GiaBan")
                        .HasColumnType("float");

                    b.Property<string>("NgheSi")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<bool>("TrongNuoc")
                        .HasColumnType("bit");

                    b.Property<string>("TuaCD")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.ToTable("DiaNhacs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GiaBan = 105000.0,
                            NgheSi = "Tuấn Vũ",
                            SoLuong = 20,
                            TrongNuoc = true,
                            TuaCD = "CD Nỗi buồn gác trọ"
                        },
                        new
                        {
                            Id = 2,
                            GiaBan = 250000.0,
                            NgheSi = "Chế Linh",
                            SoLuong = 15,
                            TrongNuoc = true,
                            TuaCD = "CD Bài tình ca đêm"
                        },
                        new
                        {
                            Id = 3,
                            GiaBan = 230000.0,
                            NgheSi = "BABYMONSTER",
                            SoLuong = 10,
                            TrongNuoc = false,
                            TuaCD = "CD BABYMONSTER"
                        },
                        new
                        {
                            Id = 4,
                            GiaBan = 150000.0,
                            NgheSi = "Mạnh Quỳnh",
                            SoLuong = 30,
                            TrongNuoc = true,
                            TuaCD = "CD Chuyện chúng mình"
                        },
                        new
                        {
                            Id = 5,
                            GiaBan = 27000.0,
                            NgheSi = "Taylor Swift",
                            SoLuong = 10,
                            TrongNuoc = false,
                            TuaCD = "CD Today's US-UK Hit "
                        },
                        new
                        {
                            Id = 6,
                            GiaBan = 220000.0,
                            NgheSi = "Văn Mai Hương",
                            SoLuong = 40,
                            TrongNuoc = true,
                            TuaCD = "CD Đoá hồng nhạc việt"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
